const leads = [
  {
    name: "Amit Sharma",
    email: "amit.sharma@technova.com",
    phone: "+91 9876543210",
    company: "TechNova",
    source: "website",
    status: "new",
    createdAt: new Date("2024-01-12"),
  },
  {
    name: "Riya Verma",
    email: "riya.verma@innosoft.com",
    phone: "+91 9123456780",
    company: "InnoSoft",
    source: "referral",
    status: "in-progress",
    createdAt: new Date("2024-03-18"),
  },
  {
    name: "Rahul Mehta",
    email: "rahul.mehta@cloudify.io",
    phone: "+91 9988776655",
    company: "Cloudify",
    source: "ads",
    status: "converted",
    createdAt: new Date("2024-05-09"),
  },
  {
    name: "Sneha Kapoor",
    email: "sneha.kapoor@nextgen.com",
    phone: "+91 9090909090",
    company: "NextGen Labs",
    source: "website",
    status: "lost",
    createdAt: new Date("2024-07-22"),
  },
  {
    name: "Arjun Singh",
    email: "arjun@datacore.com",
    phone: "+91 9345678123",
    company: "DataCore",
    source: "ads",
    status: "in-progress",
    createdAt: new Date("2024-09-14"),
  },
  {
    name: "Neha Gupta",
    email: "neha@brightedge.com",
    phone: "+91 9554433221",
    company: "BrightEdge",
    source: "referral",
    status: "new",
    createdAt: new Date("2024-11-05"),
  },

  {
    name: "Karan Malhotra",
    email: "karan@visionware.io",
    phone: "+91 9898989898",
    company: "VisionWare",
    source: "website",
    status: "converted",
    createdAt: new Date("2025-01-08"),
  },
  {
    name: "Pooja Nair",
    email: "pooja@pixelcraft.in",
    phone: "+91 9765432109",
    company: "PixelCraft",
    source: "ads",
    status: "lost",
    createdAt: new Date("2025-02-16"),
  },
  {
    name: "Vikas Yadav",
    email: "vikas@alphatech.com",
    phone: "+91 9811223344",
    company: "AlphaTech",
    source: "website",
    status: "new",
    createdAt: new Date("2025-04-11"),
  },
  {
    name: "Anjali Rao",
    email: "anjali@softbridge.com",
    phone: "+91 9678901234",
    company: "SoftBridge",
    source: "referral",
    status: "in-progress",
    createdAt: new Date("2025-06-19"),
  },
  {
    name: "Rohit Bansal",
    email: "rohit@webcore.com",
    phone: "+91 9998887776",
    company: "WebCore",
    source: "website",
    status: "new",
    createdAt: new Date("2025-08-03"),
  },
  {
    name: "Simran Kaur",
    email: "simran@marketify.com",
    phone: "+91 9311122233",
    company: "Marketify",
    source: "ads",
    status: "in-progress",
    createdAt: new Date("2025-10-27"),
  },

  {
    name: "Aditya Joshi",
    email: "aditya@infoworks.com",
    phone: "+91 9456781230",
    company: "InfoWorks",
    source: "referral",
    status: "converted",
    createdAt: new Date("2025-12-06"),
  },
  {
    name: "Nisha Patel",
    email: "nisha@bizflow.com",
    phone: "+91 9000011111",
    company: "BizFlow",
    source: "website",
    status: "lost",
    createdAt: new Date("2026-01-03"),
  },
  {
    name: "Sandeep Khanna",
    email: "sandeep@innovex.com",
    phone: "+91 9887766554",
    company: "Innovex",
    source: "ads",
    status: "new",
    createdAt: new Date("2024-02-25"),
  },
  {
    name: "Meera Iyer",
    email: "meera@techpulse.com",
    phone: "+91 9212345678",
    company: "TechPulse",
    source: "referral",
    status: "in-progress",
    createdAt: new Date("2024-06-30"),
  },
  {
    name: "Harsh Vardhan",
    email: "harsh@digisol.com",
    phone: "+91 9700012345",
    company: "DigiSol",
    source: "website",
    status: "converted",
    createdAt: new Date("2024-10-10"),
  },
  {
    name: "Kavya Nair",
    email: "kavya@brandify.com",
    phone: "+91 9822334455",
    company: "Brandify",
    source: "ads",
    status: "lost",
    createdAt: new Date("2025-03-21"),
  },
  {
    name: "Mohit Agarwal",
    email: "mohit@fintechly.com",
    phone: "+91 9567890123",
    company: "FinTechly",
    source: "referral",
    status: "new",
    createdAt: new Date("2025-05-15"),
  },
  {
    name: "Priya Saxena",
    email: "priya@startuphub.com",
    phone: "+91 9876501234",
    company: "StartupHub",
    source: "website",
    status: "in-progress",
    createdAt: new Date("2025-07-09"),
  },
  {
    name: "Rakesh Mishra",
    email: "rakesh@codewave.com",
    phone: "+91 9812345670",
    company: "CodeWave",
    source: "ads",
    status: "converted",
    createdAt: new Date("2025-09-18"),
  },
  {
    name: "Divya Malhotra",
    email: "divya@uxstudio.com",
    phone: "+91 9922113344",
    company: "UX Studio",
    source: "referral",
    status: "lost",
    createdAt: new Date("2025-11-02"),
  },
  {
    name: "Sneha Kapoor",
    email: "sneha.kapoor@nextgen.com",
    phone: "+91 9090909090",
    company: "NextGen Labs",
    source: "website",
    status: "lost",
    createdAt: new Date("2024-07-22"),
  },
  {
    name: "Arjun Singh",
    email: "arjun@datacore.com",
    phone: "+91 9345678123",
    company: "DataCore",
    source: "ads",
    status: "in-progress",
    createdAt: new Date("2024-09-14"),
  },
  {
    name: "Neha Gupta",
    email: "neha@brightedge.com",
    phone: "+91 9554433221",
    company: "BrightEdge",
    source: "referral",
    status: "new",
    createdAt: new Date("2024-11-05"),
  },
];
module.exports = leads;
